"use client";

import { useEffect, useMemo, useState } from "react";
import { TriangleAlert, X } from "lucide-react";
import { addActivity, generateId, getAppSettings, getInventory, getOrders, getProducts, getSuppliers, InventoryItem, Product, resolveSupplierName, saveOrders, saveProducts, Supplier } from "../lib/storage";

type StatusFilter = "ALL" | "OUT" | "LOW" | "ORDERED" | "ACTION";
type AlertItem = { product: Product; stock: number; minimum: number; variant: string; onOrderQuantity: number; supplier: string };

function safeNumber(value: unknown) { const numberValue = Number(value); return Number.isNaN(numberValue) ? 0 : numberValue; }
function isLowStock(stock: number, minimum: number, mode: "lt" | "lte") { return minimum > 0 && stock > 0 && (mode === "lte" ? stock <= minimum : stock < minimum); }
function productLabel(product: Product) { return product.model || product.name || product.brandUses || "Unnamed product"; }

export default function InventoryOrderPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [inventory, setInventory] = useState<InventoryItem[]>([]);
  const [orders, setOrders] = useState<ReturnType<typeof getOrders>>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [supplierFilter, setSupplierFilter] = useState("All");
  const [status, setStatus] = useState<StatusFilter>("ALL");
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [reviewing, setReviewing] = useState(false);
  const [isCreating, setIsCreating] = useState(false);

  const refresh = () => { setProducts(getProducts()); setInventory(getInventory()); setOrders(getOrders()); setSuppliers(getSuppliers()); };
  useEffect(() => { refresh(); window.addEventListener("mgb-storage-updated", refresh as EventListener); window.addEventListener("focus", refresh); return () => { window.removeEventListener("mgb-storage-updated", refresh as EventListener); window.removeEventListener("focus", refresh); }; }, []);

  const categories = useMemo(() => ["All", ...Array.from(new Set(products.map((product) => product.category).filter(Boolean))).sort()], [products]);
  const supplierNames = useMemo(() => ["All", ...Array.from(new Set(products.map((product) => resolveSupplierName(product.supplier || "", suppliers)).filter(Boolean))).sort()], [products, suppliers]);
  const alertItems = useMemo(() => {
    const settings = getAppSettings(); const stockByProduct = new Map<number, number>(); const variants = new Map<number, Set<string>>(); const onOrder = new Map<number, number>();
    inventory.forEach((item) => { stockByProduct.set(item.productId, (stockByProduct.get(item.productId) ?? 0) + safeNumber(item.stock)); if (item.variant) { const values = variants.get(item.productId) ?? new Set<string>(); values.add(item.variant); variants.set(item.productId, values); } });
    orders.filter((order) => order.status === "OPEN").forEach((order) => (order.lines?.length ? order.lines : [{ productId: order.productId, quantity: order.quantity }]).forEach((line) => onOrder.set(line.productId, (onOrder.get(line.productId) ?? 0) + safeNumber(line.quantity))));
    return products.map((product) => { const stock = stockByProduct.get(product.id) ?? 0; const minimum = safeNumber(product.minimum); return { product, stock, minimum, variant: product.sizeGauge || Array.from(variants.get(product.id) ?? []).join(", "), onOrderQuantity: onOrder.get(product.id) ?? 0, supplier: resolveSupplierName(product.supplier || "", suppliers) }; }).filter((item) => (item.stock === 0 && (settings.includeNonStockedInAlerts || item.minimum > 0)) || isLowStock(item.stock, item.minimum, settings.lowStockMode)).sort((left, right) => { const leftPriority = left.stock === 0 ? (left.onOrderQuantity ? 3 : 1) : (left.onOrderQuantity ? 4 : 2); const rightPriority = right.stock === 0 ? (right.onOrderQuantity ? 3 : 1) : (right.onOrderQuantity ? 4 : 2); return leftPriority - rightPriority || (right.minimum - right.stock) - (left.minimum - left.stock); });
  }, [inventory, orders, products, suppliers]);
  const filteredItems = useMemo(() => { const tokens = search.toLowerCase().trim().split(/\s+/).filter(Boolean); return alertItems.filter((item) => { const fields = [item.product.name, item.product.brandUses, item.product.model, item.product.sizeGauge, item.product.category, item.product.productCode, item.product.sku, item.supplier].filter(Boolean).join(" ").toLowerCase(); const matchesStatus = status === "ALL" || (status === "OUT" && item.stock === 0) || (status === "LOW" && item.stock > 0) || (status === "ORDERED" && item.onOrderQuantity > 0) || (status === "ACTION" && item.onOrderQuantity === 0); return tokens.every((token) => fields.includes(token)) && (category === "All" || item.product.category === category) && (supplierFilter === "All" || item.supplier === supplierFilter) && matchesStatus; }); }, [alertItems, category, search, status, supplierFilter]);
  const selectedItems = alertItems.filter((item) => selected[item.product.id] > 0);
  const groups = useMemo(() => new Map(selectedItems.filter((item) => item.supplier).reduce<Array<[string, AlertItem[]]>>((result, item) => { const existing = result.find(([supplier]) => supplier === item.supplier); if (existing) existing[1].push(item); else result.push([item.supplier, [item]]); return result; }, [])), [selectedItems]);
  const selectedUnits = Object.values(selected).reduce((sum, quantity) => sum + quantity, 0);
  const summary = { out: alertItems.filter((item) => item.stock === 0).length, low: alertItems.filter((item) => item.stock > 0).length, ordered: alertItems.filter((item) => item.onOrderQuantity > 0).length, action: alertItems.filter((item) => item.onOrderQuantity === 0).length };
  const filtersActive = Boolean(search || category !== "All" || supplierFilter !== "All" || status !== "ALL");

  const toggleSelected = (item: AlertItem, checked: boolean) => setSelected((current) => { const next = { ...current }; if (checked) next[item.product.id] = item.product.orderQty && item.product.orderQty > 0 ? item.product.orderQty : 0; else delete next[item.product.id]; return next; });
  const createOrders = () => {
    if (isCreating || groups.size === 0) return;
    setIsCreating(true); const orderedDate = new Date().toISOString().slice(0, 10); const existingOrders = getOrders(); const newOrders = Array.from(groups.entries()).map(([supplier, lines]) => ({ id: generateId(), productId: lines[0].product.id, productName: lines.length === 1 ? productLabel(lines[0].product) : `${supplier} purchase order`, variant: lines.length === 1 ? lines[0].variant : "", quantity: lines.reduce((sum, item) => sum + (selected[item.product.id] || 0), 0), orderedDate, supplier, status: "OPEN" as const, lines: lines.map((item) => ({ productId: item.product.id, productName: productLabel(item.product), variant: item.variant, quantity: selected[item.product.id], lastBuyPrice: item.product.lastBuyPrice })) }));
    const orderedIds = new Set(selectedItems.map((item) => item.product.id)); const updatedProducts = products.map((product) => orderedIds.has(product.id) ? { ...product, ordered: true, orderedDate } : product);
    saveOrders([...newOrders, ...existingOrders]); saveProducts(updatedProducts); setOrders([...newOrders, ...existingOrders]); setProducts(updatedProducts); addActivity(`Created ${newOrders.length} purchase order${newOrders.length === 1 ? "" : "s"} from Low / Out of Stock`); setSelected({}); setReviewing(false); setIsCreating(false);
  };

  return <div className="p-6 space-y-6 max-w-[1800px] mx-auto animate-fade-in-up">
    <div className="command-hero command-hero-inventory-order"><div className="mt-3 command-slip-icon"><TriangleAlert />Low / Out of Stock</div><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Low / Out of Stock</h1><p className="mt-3 text-sm leading-6 text-slate-600 sm:text-base">Items that need restocking.</p></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:max-w-3xl"><Metric label="Out of Stock" value={summary.out} tone="danger" /><Metric label="Low Stock" value={summary.low} tone="warning" /><Metric label="On Order" value={summary.ordered} tone="neutral" /><Metric label="Needs Action" value={summary.action} tone="warning" /></div>
    {selectedItems.length > 0 ? <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700"><span>{selectedItems.length} items selected · {selectedUnits} total units · {groups.size} suppliers</span><button type="button" onClick={() => setReviewing(true)} disabled={groups.size === 0} className="rounded-md bg-cyan-500 px-3 py-2 font-semibold text-slate-950 disabled:opacity-50">Review Orders</button></section> : null}
    <section className="glass-card p-5"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search items to restock..." className="w-full rounded-lg border border-slate-200 bg-white px-4 py-3 text-slate-900" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm text-slate-900">{categories.map((value) => <option key={value}>{value}</option>)}</select><select value={supplierFilter} onChange={(event) => setSupplierFilter(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm text-slate-900">{supplierNames.map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value as StatusFilter)} className="rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm text-slate-900"><option value="ALL">All status</option><option value="OUT">Out of Stock</option><option value="LOW">Low Stock</option><option value="ORDERED">On Order</option><option value="ACTION">Needs Action</option></select></div>{filtersActive ? <button type="button" onClick={() => { setSearch(""); setCategory("All"); setSupplierFilter("All"); setStatus("ALL"); }} className="mt-3 text-sm font-medium text-cyan-700">Clear filters</button> : null}</section>
    <section className="glass-card overflow-x-auto"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="text-lg font-semibold text-slate-950">Restock items</h2><span className="text-sm text-slate-600">{filteredItems.length} items</span></div>{filteredItems.length === 0 ? <p className="p-6 text-sm text-slate-600">{filtersActive ? "No items match these filters." : "No items currently need restocking."}</p> : <table className="min-w-[1050px] w-full text-sm text-slate-700"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-3 text-left">Select</th><th className="p-3 text-left">Product</th><th className="p-3 text-left">Current</th><th className="p-3 text-left">Minimum</th><th className="p-3 text-left">Order Qty</th><th className="p-3 text-left">Supplier</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{filteredItems.map((item) => { const isSelected = item.product.id in selected; const isOut = item.stock === 0; return <tr key={item.product.id} className="border-t border-slate-200 hover:bg-slate-50"><td className="p-3"><input type="checkbox" disabled={item.onOrderQuantity > 0} checked={isSelected} onChange={(event) => toggleSelected(item, event.target.checked)} className="h-4 w-4 rounded border-slate-300 accent-cyan-600" /></td><td className="p-3"><p className="font-medium text-slate-950">{item.product.brandUses || productLabel(item.product)}</p><p className="mt-1 text-xs text-slate-500">{productLabel(item.product)}{item.variant ? ` · ${item.variant}` : ""}</p></td><td className={`p-3 text-lg font-semibold ${isOut ? "text-rose-700" : "text-slate-950"}`}>{item.stock}</td><td className="p-3">{item.minimum || "-"}</td><td className="p-3">{item.onOrderQuantity > 0 ? `${item.onOrderQuantity} on order` : item.product.orderQty && item.product.orderQty > 0 ? item.product.orderQty : "No default"}</td><td className="p-3">{item.supplier || "NO SUPPLIER"}</td><td className="p-3"><span className={item.onOrderQuantity > 0 ? "font-medium text-cyan-700" : isOut ? "font-medium text-rose-700" : "font-medium text-amber-700"}>{item.onOrderQuantity > 0 ? "ON ORDER" : isOut ? "OUT OF STOCK" : "LOW STOCK"}</span></td></tr>; })}</tbody></table>}</section>
    {reviewing ? <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><section role="dialog" aria-modal="true" aria-labelledby="review-orders-title" className="mx-auto my-8 w-full max-w-3xl rounded-lg border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="review-orders-title" className="text-xl font-semibold text-slate-950">Review orders</h2><p className="mt-1 text-sm text-slate-600">One purchase order will be created for each supplier.</p></div><button type="button" onClick={() => setReviewing(false)} aria-label="Close review" className="text-slate-600"><X className="h-5 w-5" /></button></div>{selectedItems.some((item) => !item.supplier) ? <p className="mt-4 rounded-md border border-amber-200 bg-slate-50 p-3 text-sm text-amber-700">Items without a supplier cannot be included. Update the product supplier before creating orders.</p> : null}<div className="mt-5 space-y-5">{Array.from(groups.entries()).map(([supplier, items]) => <div key={supplier} className="border-t border-slate-200 pt-4"><div className="flex justify-between gap-4"><h3 className="font-semibold text-slate-950">{supplier}</h3><span className="text-sm text-slate-600">{items.reduce((sum, item) => sum + selected[item.product.id], 0)} units</span></div><div className="mt-3 space-y-2">{items.map((item) => <div key={item.product.id} className="grid grid-cols-[minmax(0,1fr)_110px_110px] items-center gap-3 text-sm"><span className="truncate text-slate-950">{productLabel(item.product)} {item.variant}</span><input type="number" min="1" value={selected[item.product.id] || ""} onChange={(event) => setSelected((current) => ({ ...current, [item.product.id]: safeNumber(event.target.value) }))} className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-slate-900" /><span className="text-right text-slate-600">{item.product.lastBuyPrice != null ? `$${(item.product.lastBuyPrice * (selected[item.product.id] || 0)).toFixed(2)}` : "-"}</span></div>)}</div></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-5"><span className="text-sm text-slate-600">Estimated total: ${selectedItems.reduce((sum, item) => sum + (item.product.lastBuyPrice ?? 0) * (selected[item.product.id] || 0), 0).toFixed(2)}</span><div className="flex gap-3"><button type="button" onClick={() => setReviewing(false)} className="rounded-md border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700">Back</button><button type="button" disabled={isCreating || selectedItems.some((item) => !item.supplier || !selected[item.product.id])} onClick={createOrders} className="rounded-md bg-cyan-500 px-4 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50">{isCreating ? "Creating..." : "Create Orders"}</button></div></div></section></div> : null}
  </div>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: "danger" | "warning" | "neutral" }) { const colour = value > 0 && tone === "danger" ? "text-rose-700" : value > 0 && tone === "warning" ? "text-amber-700" : "text-slate-950"; return <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3"><p className="text-sm font-medium text-slate-600">{label}</p><p className={`mt-2 text-2xl font-semibold ${colour}`}>{value}</p></div>; }